class InterestData {
  static const Map<String, List<String>> detailedInterests = {
    "Fashion & beauty": [
      "Skincare",
      "Makeup",
      "Street fashion",
      "Luxury fashion",
      "Sustainable fashion",
      "Hair care",
      "Fashion weeks",
      "Beauty tips",
      "Nail art",
      "Perfume",
      "Men's fashion",
      "Vintage fashion",
      "Fashion designers",
      "Accessories",
      "Korean beauty",
      "Fashion trends",
      "Cosmetics",
      "Plus size fashion",
      "Fashion influencers",
      "Beauty products",
    ],
    "Outdoors": [
      "Hiking",
      "Camping",
      "Rock climbing",
      "Mountain biking",
      "Kayaking",
      "Fishing",
      "Birdwatching",
      "Skiing",
      "Surfing",
      "National parks",
      "Trail running",
      "Backpacking",
      "Wildlife",
      "Adventure travel",
      "Outdoor photography",
      "Survival skills",
      "Beach activities",
      "Mountaineering",
      "Outdoor gear",
      "Nature conservation",
    ],
    "Arts & culture": [
      "Contemporary art",
      "Classical music",
      "Theater",
      "Museums",
      "Literature",
      "Poetry",
      "Dance",
      "Art history",
      "Street art",
      "Film festivals",
      "Cultural events",
      "Art galleries",
      "Opera",
      "Sculpture",
      "Photography",
      "Architecture",
      "Folk art",
      "Digital art",
      "Art exhibitions",
      "Cultural heritage",
    ],
    "Animation & comics": [
      "Anime",
      "Manga",
      "Marvel Comics",
      "DC Comics",
      "Studio Ghibli",
      "Webcomics",
      "Comic art",
      "Animation studios",
      "Cartoon Network",
      "Disney animation",
      "Indie comics",
      "Comic conventions",
      "Character design",
      "Graphic novels",
      "Animation techniques",
      "Voice acting",
      "Pixar",
      "Comic collecting",
      "Animated movies",
      "Cosplay",
    ],
    "Business & finance": [
      "Stock market",
      "Cryptocurrency",
      "Startups",
      "Investment",
      "Personal finance",
      "Real estate",
      "Entrepreneurship",
      "Marketing",
      "Economics",
      "Financial planning",
      "Business strategy",
      "Leadership",
      "Venture capital",
      "Digital marketing",
      "E-commerce",
      "Business news",
      "Financial technology",
      "Small business",
      "Corporate finance",
      "Business analytics",
    ],
    "Food": [
      "Cooking",
      "Baking",
      "Restaurant reviews",
      "Wine & spirits",
      "Healthy eating",
      "Food photography",
      "International cuisine",
      "Vegetarian & vegan",
      "Street food",
      "Coffee culture",
      "Food trends",
      "Recipe development",
      "Food science",
      "Culinary arts",
      "Food history",
      "Desserts",
      "BBQ & grilling",
      "Food sustainability",
      "Mixology",
      "Food festivals",
    ],
    "Travel": [
      "Adventure travel",
      "Budget travel",
      "Luxury travel",
      "Solo travel",
      "Backpacking",
      "Cultural tourism",
      "Food tourism",
      "Travel photography",
      "Road trips",
      "Travel tips",
      "Digital nomad",
      "Eco tourism",
      "City guides",
      "Travel gear",
      "Hotels & resorts",
      "Travel blogging",
      "Historical sites",
      "Beach destinations",
      "Mountain destinations",
      "Travel planning",
    ],
    "Entertainment": [
      "Movies",
      "TV shows",
      "Celebrity news",
      "Streaming services",
      "Film reviews",
      "Award shows",
      "Reality TV",
      "Stand-up comedy",
      "Podcasts",
      "Live events",
      "Music festivals",
      "Theater productions",
      "Entertainment news",
      "Behind the scenes",
      "Movie premieres",
      "TV series",
      "Film industry",
      "Documentaries",
      "Web series",
      "Entertainment tech",
    ],
    "Music": [
      "Pop music",
      "Rock",
      "Hip hop",
      "Jazz",
      "Classical",
      "Electronic music",
      "Music production",
      "Music festivals",
      "Concert tours",
      "Music gear",
      "Indie music",
      "Music history",
      "Music theory",
      "Vinyl records",
      "Music streaming",
      "Music videos",
      "Music industry",
      "Live performances",
      "Music education",
      "Music technology",
    ],
    "Gaming": [
      "PC gaming",
      "Console gaming",
      "Mobile games",
      "Esports",
      "Game development",
      "Gaming news",
      "Retro gaming",
      "Game reviews",
      "Gaming hardware",
      "Streaming",
      "RPG games",
      "FPS games",
      "Strategy games",
      "Gaming community",
      "Game design",
      "Virtual reality",
      "Gaming events",
      "Indie games",
      "Gaming culture",
      "Gaming accessories",
    ],
    "Technology": [
      "Artificial Intelligence",
      "Cybersecurity",
      "Blockchain",
      "Cloud computing",
      "Mobile tech",
      "Programming",
      "Tech news",
      "Gadgets",
      "Internet of Things",
      "Tech startups",
      "Web development",
      "Data science",
      "Tech reviews",
      "Digital privacy",
      "Tech industry",
      "Robotics",
      "5G technology",
      "Tech innovation",
      "Software development",
      "Tech education",
    ],
    "Sports": [
      "Football",
      "Basketball",
      "Baseball",
      "Soccer",
      "Tennis",
      "Golf",
      "Swimming",
      "Athletics",
      "Martial arts",
      "Cycling",
      "Winter sports",
      "Sports news",
      "Fantasy sports",
      "Sports analytics",
      "Extreme sports",
      "Olympic sports",
      "Sports technology",
      "Sports medicine",
      "Sports culture",
      "Sports gear",
    ],
    "Health & fitness": [
      "Workout routines",
      "Nutrition",
      "Mental health",
      "Yoga",
      "Running",
      "Weight training",
      "CrossFit",
      "Meditation",
      "Wellness",
      "Personal training",
      "Fitness tech",
      "Health tips",
      "Diet plans",
      "Sports medicine",
      "Recovery techniques",
      "Home workouts",
      "Fitness challenges",
      "Health tracking",
      "Fitness gear",
      "Healthy lifestyle",
    ],
    "Science": [
      "Physics",
      "Biology",
      "Chemistry",
      "Astronomy",
      "Environmental science",
      "Neuroscience",
      "Space exploration",
      "Climate change",
      "Scientific research",
      "Genetics",
      "Quantum mechanics",
      "Marine biology",
      "Science news",
      "Laboratory work",
      "Science education",
      "Scientific discoveries",
      "Earth science",
      "Medical science",
      "Science technology",
      "Science history",
    ],
    "Education": [
      "Online learning",
      "Higher education",
      "K-12 education",
      "Educational technology",
      "Language learning",
      "Professional development",
      "Study tips",
      "Academic research",
      "Teaching methods",
      "Educational resources",
      "Distance learning",
      "Special education",
      "Educational psychology",
      "Curriculum development",
      "Student life",
      "Educational policy",
      "Adult education",
      "Early childhood education",
      "Educational leadership",
      "STEM education",
    ],
    "Photography": [
      "Portrait photography",
      "Landscape photography",
      "Street photography",
      "Wildlife photography",
      "Mobile photography",
      "Photo editing",
      "Camera gear",
      "Black and white",
      "Photography tips",
      "Fashion photography",
      "Travel photography",
      "Macro photography",
      "Night photography",
      "Documentary photography",
      "Photography composition",
      "Film photography",
      "Photography events",
      "Photography history",
      "Photography business",
      "Photography art",
    ],
  };
}
